openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  version: 1.0.11
servers:
- url: /
tags:
- name: student
  description: Everything about the students
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /Student:
    post:
      description: Add a new pet to the store
      operationId: addPet
      responses:
        "200":
          description: Successful operation
        "405":
          description: Invalid input
  /student/find student by name:
    get:
      description: "Multiple tags can be provided with comma separated strings. Use\
        \ tag1, tag2, tag3 for testing."
      operationId: findPetsByTags
      parameters:
      - name: tags
        in: query
        description: Tags to filter by
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid tag value
components:
  schemas:
    Student:
      type: object
      properties:
        STD:
          type: integer
          format: int64
          example: 10
        Age:
          type: integer
          format: int32
          example: 7
        birthdate:
          type: string
          format: date-time
        name:
          type: string
          description: Order Status
          example: approved
          enum:
          - placed
          - approved
          - delivered
        complete:
          type: boolean
      xml:
        name: order
